when@dev:
    
web_profiler:
    toolbar: true               # active la toolbar Symfony
 

framework:
    profiler:
        only_exceptions: false  # profiler actif pour toutes les requêtes, pas seulement les exceptions


when@test:
    framework:
        profiler:
            collect: false
            collect_serializer_data: true
