services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-php-app
    ports:
      - "8443:443"  # Apache HTTPS
      - "8080:80"   # Apache HTTP
    volumes:
      - /home/billy/Team-Rocket/teamrocket:/var/www/html:cached
      - ./docker/apache/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf:ro
      - ./docker/php/conf.d/memory.ini:/usr/local/etc/php/conf.d/memory.ini

    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - database
      - mercure
    working_dir: /var/www/html
    

  database:
    image: postgres:16-alpine
    container_name: my-postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: teamrocketforever
    volumes:
      - database_data:/var/lib/postgresql/data

  mercure:
    image: dunglas/mercure
    container_name: mercure-hub
    restart: unless-stopped
    environment:
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://127.0.0.1:8000
    ports:
      - "8081:80"

volumes:
  database_data:
