# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:
    env(MERCURE_PUBLIC_URL): ''

twig:
    globals:
        MERCURE_PUBLIC_URL: '%env(MERCURE_PUBLIC_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $publisherJwt: '@=service("App\\Service\\MercureJwtFactory").createPublisherJwt()'

    App\Service\MercureJwtFactory:
        arguments:
            $publisherJwtKey: '%env(MERCURE_PUBLISHER_JWT_KEY)%'

    App\:
        resource: '../src/'

    App\EventListener\ChatDoctrineListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    App\EventListener\SendChatMercureListener:
        tags:
            - { name: kernel.event_listener, event: 'App\\Event\\ChatMessageEvent', method: onChatMessage }